"""initial_single_creator_os

Revision ID: 3e7aa64a7df9
Revises: 
Create Date: 2026-02-12 19:30:06.473780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e7aa64a7df9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('source_type', sa.Enum('YOUTUBE', 'INSTAGRAM', 'WHATSAPP', 'LOCAL', name='platform'), nullable=True),
    sa.Column('content_type', sa.Enum('VIDEO', 'AUDIO', name='contenttype'), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'DOWNLOADING', 'PROCESSING', 'READY', 'FAILED', name='contentstatus'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_assets_created_at'), 'content_assets', ['created_at'], unique=False)
    op.create_index(op.f('ix_content_assets_id'), 'content_assets', ['id'], unique=False)
    op.create_index(op.f('ix_content_assets_status'), 'content_assets', ['status'], unique=False)
    op.create_index(op.f('ix_content_assets_title'), 'content_assets', ['title'], unique=False)
    op.create_table('strategy_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('decision', sa.JSON(), nullable=True),
    sa.Column('agent_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_decisions_created_at'), 'strategy_decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_strategy_decisions_id'), 'strategy_decisions', ['id'], unique=False)
    op.create_index(op.f('ix_strategy_decisions_status'), 'strategy_decisions', ['status'], unique=False)
    op.create_table('clips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('s3_url', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'READY', 'POSTED', 'FAILED', name='clipstatus'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('virality_score', sa.Float(), nullable=True),
    sa.Column('hook_strength', sa.Float(), nullable=True),
    sa.Column('emotion_tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['content_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clips_created_at'), 'clips', ['created_at'], unique=False)
    op.create_index(op.f('ix_clips_id'), 'clips', ['id'], unique=False)
    op.create_index(op.f('ix_clips_status'), 'clips', ['status'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clip_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.Enum('YOUTUBE', 'INSTAGRAM', 'WHATSAPP', 'LOCAL', name='platform'), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('performance_metrics', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'POSTING', 'POSTED', 'FAILED', name='poststatus'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_created_at'), 'posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_index(op.f('ix_posts_scheduled_time'), 'posts', ['scheduled_time'], unique=False)
    op.create_index(op.f('ix_posts_status'), 'posts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_status'), table_name='posts')
    op.drop_index(op.f('ix_posts_scheduled_time'), table_name='posts')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_clips_status'), table_name='clips')
    op.drop_index(op.f('ix_clips_id'), table_name='clips')
    op.drop_index(op.f('ix_clips_created_at'), table_name='clips')
    op.drop_table('clips')
    op.drop_index(op.f('ix_strategy_decisions_status'), table_name='strategy_decisions')
    op.drop_index(op.f('ix_strategy_decisions_id'), table_name='strategy_decisions')
    op.drop_index(op.f('ix_strategy_decisions_created_at'), table_name='strategy_decisions')
    op.drop_table('strategy_decisions')
    op.drop_index(op.f('ix_content_assets_title'), table_name='content_assets')
    op.drop_index(op.f('ix_content_assets_status'), table_name='content_assets')
    op.drop_index(op.f('ix_content_assets_id'), table_name='content_assets')
    op.drop_index(op.f('ix_content_assets_created_at'), table_name='content_assets')
    op.drop_table('content_assets')
    # ### end Alembic commands ###
