"""Add attendees to event model

Revision ID: c94a64ac5ad5
Revises: a1b2c3
Create Date: 2026-02-13 11:21:04.635858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c94a64ac5ad5'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('attendees', sa.String(), nullable=True))
    op.add_column('whatsapp_messages', sa.Column('status', sa.String(), nullable=True))
    op.add_column('whatsapp_messages', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_messages', 'error_message')
    op.drop_column('whatsapp_messages', 'status')
    op.drop_column('events', 'attendees')
    # ### end Alembic commands ###
